# Main configuration file for STAMP.
# 
# NOTE: you may use environment variables in this file, e.g. ${oc.env:STAMP_RESOURCES_DIR}.
# The STAMP_RESOURCES_DIR environment variable is a special environment variable that, if not set, will be set to the resources/ directory relative to the config.yaml file.

preprocessing:
  output_dir: # Path to save features to
  wsi_dir: # Path of where the whole-slide images are.
  cache_dir: ${preprocessing.output_dir}/cache # Directory to store resulting slide JPGs
  patch_size: 224 # Size of the square patch to tessellate
  mpp: 1.1428571429 # Microns-per-pixel value for slide resolution (default: 256/224)
  cores: 8 # CPU cores to use
  norm: true # Perform Macenko normalisation
  del_slide: false # Remove the original slide after processing
  only_feature_extraction: false # Only perform feature extraction
  device: cpu # device to run feature extraction on (cpu, cuda, cuda:0, etc.)
  normalization_template: ${oc.env:STAMP_RESOURCES_DIR}/normalization_template.jpg # Path to normalization template
  model_path: ${oc.env:STAMP_RESOURCES_DIR}/ctranspath.pth  # Path of where model for the feature extractor is

modeling:
  clini_table: # Path to clini_excel file
  slide_csv: # Path to slide_csv file
  feature_dir: ${preprocessing.output_dir} # Path to feature directory
  output_dir: # Path to output directory
  target_label: # Target label
  categories: # Categories (list), leave empty to automatically infer based on unique values in the target_label column
  cat_labels: [] # Extra input category labels (list, can be empty)
  cont_labels: [] # Extra input continuous labels (list, can be empty)
  n_splits: 5 # Number of splits for cross-validation (only applicable to cross-validation)
  model_path: ${modeling.output_dir}/... # Path to saved model (only applicable to deployment)

statistics:
  pred_csvs: # Paths to prediction CSVs to plot ROC curves for
    - ${modeling.output_dir}/patient-preds.csv
  target_label: # ${modeling.target_label} # Target label
  true_class: # Class to consider as positive
  output_dir: ${modeling.output_dir}/roc # Path to save ROC curve and statistics to
  n_bootstrap_samples: 1000 # Number of bootstrapping samples to take for confidence interval generation
  figure_width: 3.8 # Width of the figure in inches
  threshold_cmap: # Draw curve with threshold color

heatmaps: